Repository uwblueprint/richmond-centre-for-disability, pull requests merged in 2021-09, with the labels that each got.

#59 [Misc] Add sample data to staging database
  .gitignore
  components/requests/PersonalInformationCard.tsx
  lib/applicants/field-resolvers.ts
  lib/applicants/schema.ts
  lib/graphql/types.ts
  lib/scripts/oneoff/backup/populate-db-09-13-21.ts
  lib/scripts/oneoff/populate-db-09-13-21.js
  package.json
  prisma/dev-seed-utils/applicants.ts
  prisma/dev-seed-utils/application-processings.ts
  prisma/dev-seed-utils/applications.ts
  prisma/dev-seed-utils/guardians.ts
  prisma/dev-seed-utils/medical-information.ts
  prisma/dev-seed-utils/permits.ts
  prisma/dev-seed-utils/physicians.ts
  prisma/schema.prisma
  prisma/schema.sql
  prisma/types.ts
  yarn.lock
Labels: needs dev review

#61 [Fix] Fix View Permit Holder page not rendering any cards
  lib/applicants/schema.ts
  lib/graphql/types.ts
Labels: needs dev review

#58 [Fix] Fix incorrect dates displayed
  components/permit-holders/AppHistoryCard.tsx
  components/permit-holders/AttachedFilesCard.tsx
  components/permit-holders/MedicalHistoryCard.tsx
  components/permit-holders/PersonalInformationCard.tsx
  components/permit-holders/modals/EditUserInformationModal.tsx
  components/permit-holders/modals/MedicalHistoryModal.tsx
  components/requests/modals/EditReasonForReplacementModal.tsx
  lib/utils/format.ts
  pages/admin/index.tsx
  pages/admin/permit-holders.tsx
  pages/verify-identity.tsx
Labels: needs dev review, needs design review

#62 [Fix] Fix seeded users not having RCD user ID
  lib/scripts/oneoff/populate-db-09-13-21.js
  prisma/dev-seed-utils/applicants.ts
  prisma/dev-seed-utils/application-processings.ts
  prisma/dev-seed-utils/applications.ts
  prisma/dev-seed-utils/guardians.ts
  prisma/dev-seed-utils/medical-information.ts
  prisma/dev-seed-utils/permits.ts
  prisma/dev-seed-utils/physicians.ts
  prisma/dev-seed-utils/replacements.ts
Labels: needs dev review

#60 [Fix] Update physician on permit holder page when MSP is updated
  components/requests/modals/EditDoctorInformationModal.tsx
  lib/graphql/types.ts
  lib/medical-information/schema.ts
  lib/physicians/resolvers.ts
  lib/physicians/schema.ts
  pages/admin/permit-holder/[permitHolderId].tsx
  tools/pages/admin/permit-holders/update-medical-information.tsx
  tools/pages/admin/permit-holders/upsert-physician.ts
Labels: needs dev review

#63 [Feature] Create Admin Management Table Frontend
  pages/admin/admin-management.tsx
  public/assets/three-dots.svg
  tools/theme/colors.ts
Labels: needs design review

#65 [Fix] Show correct rcdUserId in requests and permit holders tables
  pages/admin/index.tsx
  pages/admin/permit-holders.tsx
  tools/pages/admin/index.ts
  tools/pages/permit-holders/permit-holders-table.ts
Labels: needs dev review, needs design review

#67 [Fix] Requests Table search by user ID not working
  lib/applicants/resolvers.ts
  lib/applications/resolvers.ts
Labels: ready to merge ✅

#68 [Feature] Update employee endpoint
  lib/employees/errors.ts
  lib/employees/resolvers.ts
  lib/employees/schema.ts
  lib/graphql/resolvers.ts
  lib/graphql/schema.ts
  lib/graphql/types.ts
Labels: ready to merge ✅

#64 [Feature] Build confirm delete admin modal
  components/admin-management/ConfirmDeleteAdminModal.tsx
  pages/admin/admin-management.tsx
  tools/pages/admin-management/types.ts
  tools/theme/colors.ts
Labels: ready to merge ✅

#71 [Feature] Add sorting to employees API
  lib/employees/resolvers.ts
  lib/employees/schema.ts
  lib/graphql/schema.ts
  lib/graphql/types.ts
Labels: ready to merge ✅

#70 [Feature] Build Add new user and Edit user Modal Frontend
  components/admin-management/AdminModal.tsx
  pages/admin/admin-management.tsx
Labels: ready to merge ✅
