Repository uwblueprint/richmond-centre-for-disability, pull requests merged in 2022-01, with the labels that each got.

#123 [Bug fix] Replace phone number field with string input field
  pages/verify-identity.tsx
Labels: ready to merge ✅

#121 [Feature] Add email updates checkbox to PermitHolderInformationForm
  components/admin/requests/PersonalInformationCard.tsx
  components/admin/requests/forms/PermitHolderInformationForm.tsx
  components/admin/requests/modals/EditPermitHolderInformationModal.tsx
  lib/applications/resolvers.ts
  lib/applications/schema.ts
  lib/graphql/resolvers.ts
  lib/graphql/types.ts
  pages/admin/request/[id].tsx
  pages/admin/request/create-renewal.tsx
  pages/admin/request/create-replacement.tsx
  pages/renew.tsx
  prisma/schema.prisma
  prisma/schema.sql
  tools/components/admin/requests/forms/types.ts
  tools/components/admin/requests/personal-information-card.ts
  tools/pages/admin/requests/queries.ts
  tools/pages/admin/requests/types.ts
Labels: ready to merge ✅

#119 [Feature] Build CSV generation API for permit holders
  lib/applicants/resolvers.ts
  lib/applicants/schema.ts
  lib/applications/resolvers.ts
  lib/graphql/resolvers.ts
  lib/graphql/schema.ts
  lib/graphql/types.ts
Labels: don't merge

#124 [Fix] Various bug fixes
  components/admin/Layout.tsx
  components/admin/permit-holders/MedicalHistoryCard.tsx
  components/admin/permit-holders/PermitHolderHeader.tsx
  components/admin/reports/GenerateReportModal.tsx
  pages/admin/admin-management.tsx
  pages/admin/index.tsx
  pages/admin/login.tsx
  pages/admin/permit-holder/[id].tsx
  pages/admin/permit-holders.tsx
  pages/admin/request/create-renewal.tsx
  pages/admin/request/create-replacement.tsx
  pages/index.tsx
  pages/renew.tsx
  pages/verify-identity.tsx
Labels: ready to merge ✅

#122 [Feature] Build create new APP endpoint
  .gitignore
  components/admin/permit-holders/modals/MedicalHistoryModal.tsx
  components/admin/requests/forms/new-applications/PhysicianAssessmentForm.tsx
  lib/application-processing/resolvers.ts
  lib/applications/resolvers.ts
  lib/applications/schema.ts
  lib/graphql/resolvers.ts
  lib/graphql/schema.ts
  lib/graphql/types.ts
  lib/medical-information/schema.ts
  prisma/dev-seed-utils/applications.ts
  prisma/dev-seed-utils/medical-information.ts
  prisma/schema.prisma
  prisma/schema.sql
  prisma/types.ts
  tools/components/admin/requests/forms/types.ts
  tools/pages/admin/permit-holders/get-permit-holder.ts
  tools/pages/admin/permit-holders/types.ts
  tools/pages/admin/requests/types.ts
  tsconfig.json
  yarn.lock
Labels: ready to merge ✅

#127 [Fix] Make doctor phone number field in applicant renewal form required
  pages/renew.tsx
Labels: ready to merge ✅

#128 [Hotfix] Fix yarn.lock file
  yarn.lock
Labels: needs dev review

#115 [Feature] Setup Shopify Checkout
  .env.sample
  package.json
  pages/renew.tsx
  prisma/schema.prisma
  prisma/schema.sql
  types/shopify-buy.d.ts
  yarn.lock
Labels: ready to merge ✅

#130 [Hotfix] Remove deprecated fields from GraphQL queries
  lib/graphql/types.ts
  lib/medical-information/schema.ts
  tools/pages/admin/permit-holders/get-permit-holder.ts
  tools/pages/admin/requests/queries.ts
Labels: needs dev review

#133 [Fix] Fix applicants endpoint filter
  lib/applicants/resolvers.ts
  pages/admin/permit-holders.tsx
  tools/admin/permit-holders/permit-holders-table.ts
Labels: ready to merge ✅

#134 [Fix] Revert applicants endpoint and add permits seeding
  components/admin/permit-holders/app-history/Card.tsx
  lib/applicants/resolvers.ts
  pages/admin/permit-holders.tsx
  prisma/dev-seed-utils/permits.ts
  prisma/seed.ts
  prisma/types.ts
  tools/admin/permit-holders/permit-holders-table.ts
Labels: ready to merge ✅

#135 [Fix] Account for existing permit holder when creating and completing new APP applications
  lib/application-processing/resolvers.ts
  lib/applications/resolvers.ts
  lib/applications/schema.ts
  lib/graphql/types.ts
  prisma/schema.sql
Labels: ready to merge ✅
