Repository uwblueprint/richmond-centre-for-disability, pull requests merged in 2022-05, with the labels that each got.

#177 [Improvement] Upload Permit Holders report to S3
  components/admin/permit-holders/reports/GenerateModal.tsx
  lib/graphql/types.ts
  lib/reports/resolvers.ts
  lib/reports/schema.ts
  tools/admin/permit-holders/graphql/generate-report.ts
Labels: ready to merge ✅

#176 [Feature] Upload accounting report to S3
  lib/graphql/types.ts
  lib/reports/resolvers.ts
  lib/reports/schema.ts
  pages/admin/reports.tsx
  tools/admin/permit-holders/graphql/generate-report.ts
Labels: ready to merge ✅

#180 [Fix] Disable edit on cards when review request completed
  pages/admin/request/[id].tsx
Labels: ready to merge ✅

#179 [Fix] Prevent API updates to applications if review step is completed
  lib/applications/resolvers.ts
  lib/reports/resolvers.ts
Labels: ready to merge ✅

#181 [Fix] Remove more actions dropdown for rejected request
  components/admin/requests/Header.tsx
Labels: ready to merge ✅

#171 [Improvement] Update view permit holder page
  components/admin/PermitTypeBadge.tsx
  components/admin/permit-holders/Header.tsx
  components/admin/permit-holders/additional-notes/Modal.tsx
  components/admin/permit-holders/app-history/Card.tsx
  components/admin/permit-holders/app-history/Card/AppHistoryRecord.tsx
  components/admin/permit-holders/app-history/Card/index.tsx
  components/admin/permit-holders/attached-files/Card.tsx
  components/admin/permit-holders/current-application/Card/AdditionalInformationSection.tsx
  components/admin/permit-holders/current-application/Card/AttachedFilesSection.tsx
  components/admin/permit-holders/current-application/Card/CardSection.tsx
  components/admin/permit-holders/current-application/Card/Header.tsx
  components/admin/permit-holders/current-application/Card/MedicalInformationSection.tsx
  components/admin/permit-holders/current-application/Card/index.tsx
  components/admin/permit-holders/guardian-information/Card.tsx
  components/admin/permit-holders/medical-history/Card.tsx
  components/admin/permit-holders/table/ConfirmSetInactiveModal.tsx
  components/admin/requests/guardian-information/EditModal.tsx
  components/admin/requests/guardian-information/Form.tsx
  components/admin/requests/guardian-information/PoaFormUploadField.tsx
  components/admin/requests/processing/TaskCardUploadStep.tsx
  components/admin/requests/processing/TasksCard.tsx
  lib/applicants/field-resolvers.ts
  lib/applicants/resolvers.ts
  lib/applicants/schema.ts
  lib/application-processing/resolvers.ts
  lib/applications/field-resolvers.ts
  lib/applications/resolvers.ts
  lib/applications/schema.ts
  lib/graphql/resolvers.ts
  lib/graphql/types.ts
  lib/guardian/field-resolvers.ts
  lib/guardian/schema.ts
  lib/permits/field-resolvers.ts
  lib/utils/s3-utils.ts
  pages/admin/permit-holder/[id].tsx
  pages/admin/request/create-new.tsx
  prisma/schema.prisma
  prisma/schema.sql
  tools/admin/permit-holders/app-history.ts
  tools/admin/permit-holders/current-application.ts
  tools/admin/permit-holders/guardian-information.ts
  tools/admin/permit-holders/view-permit-holder.ts
  tools/admin/requests/create-new.ts
  tools/admin/requests/guardian-information.ts
  tools/string.ts
  tools/theme/components/badge.ts
Labels: ready to merge ✅

#183 [Feature] Create Additional Information Edit Modal
  components/admin/requests/additional-questions/Card.tsx
  components/admin/requests/additional-questions/EditModal.tsx
  tools/admin/requests/additional-questions.ts
Labels: ready to merge ✅

#188 Add loading states to applicant flow
  pages/renew.tsx
Labels: needs dev review, needs design review

#187 [Improvement] Hookup set as active modal to setApplicantAsActive endpoint
  components/admin/permit-holders/Header.tsx
  components/admin/permit-holders/table/ConfirmSetActiveModal.tsx
  components/admin/permit-holders/table/ConfirmSetInactiveModal.tsx
  pages/admin/permit-holders.tsx
  tools/admin/permit-holders/permit-holders-table.ts
Labels: ready to merge ✅

#184 [Feature] Create Physician Assessment Card
  components/admin/requests/physician-assessment/Card.tsx
  pages/admin/request/[id].tsx
  tools/admin/requests/physician-assessment.ts
Labels: ready to merge ✅

#172 [Improvement] Add layout changes and footer to Request Pages
  components/admin/requests/Footer.tsx
  components/admin/requests/Header.tsx
  components/admin/requests/additional-questions/Card.tsx
  components/admin/requests/doctor-information/Card.tsx
  components/admin/requests/guardian-information/Card.tsx
  components/admin/requests/guardian-information/EditModal.tsx
  components/admin/requests/payment-information/Card.tsx
  components/admin/requests/permit-holder-information/Card.tsx
  components/admin/requests/physician-assessment/Card.tsx
  components/admin/requests/processing/ProcessingFooter.tsx
  components/admin/requests/processing/RejectRequestModal.tsx
  components/admin/requests/processing/TaskStep.tsx
  components/admin/requests/processing/TasksCard.tsx
  components/admin/requests/reason-for-replacement/Card.tsx
  lib/application-processing/resolvers.ts
  lib/applications/resolvers.ts
  lib/applications/schema.ts
  lib/graphql/resolvers.ts
  lib/graphql/schema.ts
  lib/graphql/types.ts
  lib/utils/format.ts
  pages/admin/request/[id].tsx
  tools/admin/requests/guardian-information.ts
  tools/admin/requests/processing-tasks-card.ts
  tools/admin/requests/view-request.ts
Labels: needs dev review, needs design review

#186 [Feature] Guardian/POA Form Validation Refactoring
  components/admin/requests/guardian-information/Form.tsx
  lib/applications/validation.ts
  lib/guardian/validation.ts
  pages/admin/request/create-new.tsx
Labels: ready to merge ✅

#189 [Improvement] Added Loading State Spinners to Request & Permit Holder Tables
  components/Table.tsx
  pages/admin/index.tsx
  pages/admin/permit-holders.tsx
Labels: ready to merge ✅

#182 [Improvement] Additional Notes API + Hookup
  components/admin/permit-holders/Header.tsx
  components/admin/permit-holders/additional-notes/Modal.tsx
  lib/applicants/resolvers.ts
  lib/applicants/schema.ts
  lib/graphql/resolvers.ts
  lib/graphql/schema.ts
  lib/graphql/types.ts
  tools/admin/permit-holders/additional-notes.ts
Labels: ready to merge ✅

#190 [Feature] Applicant facing renewal form validation
  lib/applications/validation.ts
  pages/renew.tsx
Labels: ready to merge ✅

#193 [Improvement] Add Loading States to Processing Task Card
  components/admin/requests/processing/ReviewInformationStep.tsx
  components/admin/requests/processing/TaskCardUploadStep.tsx
  components/admin/requests/processing/TasksCard.tsx
Labels: needs design review

#195 [Improvement] Empty State Components Added to Request & Permit Holder Tables
  components/EmptyMessage.tsx
  pages/admin/index.tsx
  pages/admin/permit-holders.tsx
  pages/admin/reports.tsx
Labels: ready to merge ✅

#185 [Feature] Doctor Information Form Validation Refactoring
  components/admin/permit-holders/doctor-information/Card.tsx
  components/admin/requests/doctor-information/EditModal.tsx
  components/admin/requests/doctor-information/Form.tsx
  lib/applicants/schema.ts
  lib/applications/schema.ts
  lib/applications/validation.ts
  lib/graphql/types.ts
  lib/physicians/schema.ts
  lib/physicians/validation.ts
  pages/admin/request/[id].tsx
  pages/admin/request/create-new.tsx
  pages/admin/request/create-renewal.tsx
  pages/api/auth/[...nextauth].ts
  pages/renew.tsx
  prisma/dev-seed-utils/applicants.ts
  prisma/dev-seed-utils/applications.ts
  prisma/schema.prisma
  prisma/schema.sql
  tools/admin/permit-holders/doctor-information.ts
  tools/admin/requests/create-new.ts
  tools/admin/requests/doctor-information.ts
Labels: needs dev review

#196 [Feature] Additional questions form validation
  components/admin/requests/additional-questions/EditModal.tsx
  lib/applications/validation.ts
Labels: ready to merge ✅

#197 [Feature] Edit guardian form validation
  components/admin/requests/guardian-information/EditModal.tsx
  lib/guardian/validation.ts
Labels: ready to merge ✅

#198 [Fix] Prevent applicants from submitting multiple renewal requests
  pages/renew.tsx
Labels: ready to merge ✅

#203 [Improvement] Add omitGuardianPoa to update APIs for applicants
  lib/applicants/field-resolvers.ts
  lib/applicants/resolvers.ts
  lib/applicants/schema.ts
  lib/graphql/types.ts
Labels: ready to merge ✅

#204 [Feature] Payment form backend validation
  components/admin/requests/payment-information/Card.tsx
  components/admin/requests/payment-information/EditModal.tsx
  components/form/ValidationErrorAlert.tsx
  lib/applications/resolvers.ts
  lib/applications/schema.ts
  lib/applications/validation.ts
  lib/graphql/types.ts
  tools/admin/requests/payment-information.ts
Labels: ready to merge ✅

#201 [Audit] Audit datetime timezones and formatting
  components/admin/permit-holders/Typeahead.tsx
  components/admin/permit-holders/app-history/Card/AppHistoryRecord.tsx
  components/admin/permit-holders/current-application/Card/Header.tsx
  components/admin/permit-holders/current-application/Card/MedicalInformationSection.tsx
  components/admin/permit-holders/medical-history/Modal.tsx
  components/admin/permit-holders/permit-holder-information/Card.tsx
  components/admin/permit-holders/permit-holder-information/EditModal.tsx
  components/admin/requests/Header.tsx
  components/admin/requests/create/SelectedPermitHolderCard.tsx
  components/admin/requests/permit-holder-information/Card.tsx
  components/admin/requests/permit-holder-information/Form.tsx
  components/admin/requests/physician-assessment/Card.tsx
  components/admin/requests/processing/TaskStep.tsx
  components/admin/requests/reason-for-replacement/Card.tsx
  components/admin/requests/reason-for-replacement/Form.tsx
  lib/application-processing/resolvers.ts
  lib/invoices/utils.ts
  lib/reports/resolvers.ts
  lib/utils/date.ts
  lib/utils/format.ts
  package.json
  pages/admin/index.tsx
  pages/admin/permit-holders.tsx
  pages/admin/request/create-new.tsx
  yarn.lock
Labels: ready to merge ✅

#192 [Feature] Build Physician Assessment Edit Modal
  components/admin/requests/physician-assessment/Card.tsx
  components/admin/requests/physician-assessment/EditModal.tsx
  components/admin/requests/physician-assessment/Form.tsx
  lib/applications/resolvers.ts
  lib/applications/schema.ts
  lib/graphql/schema.ts
  lib/graphql/types.ts
  lib/physicians/validation.ts
  pages/admin/request/create-new.tsx
  prisma/schema.prisma
  prisma/schema.sql
  tools/admin/requests/additional-questions.ts
  tools/admin/requests/create-new.ts
  tools/admin/requests/physician-assessment.ts
Labels: ready to merge ✅

#200 [Fix] Add phone number formatting
  components/admin/permit-holders/doctor-information/Card.tsx
  components/admin/permit-holders/guardian-information/Card.tsx
  components/admin/permit-holders/permit-holder-information/Card.tsx
  lib/applicants/resolvers.ts
  lib/applications/resolvers.ts
  pages/admin/permit-holders.tsx
Labels: needs dev review
