Repository uwblueprint/richmond-centre-for-disability, pull requests merged in 2022-03, with the labels that each got.

#146 [Feature] New APP Request S3 Hookup
  .env.sample
  lib/applications/resolvers.ts
  lib/applications/schema.ts
  lib/graphql/types.ts
  package.json
  pages/admin/request/create-new.tsx
  pages/api/s3-upload.ts
  prisma/schema.prisma
  prisma/schema.sql
  tools/admin/requests/create-new.ts
  tools/admin/requests/guardian-information.ts
  yarn.lock
Labels: ready to merge ✅

#147 [Feature] Make S3 Upload Links Private
  lib/utils/upload-to-s3.ts
  pages/admin/request/create-new.tsx
  pages/api/s3-upload.ts
Labels: ready to merge ✅

#149 [Fix] Fix payment confirmation email not sending in staging
  pages/api/payment-received.ts
Labels: ready to merge ✅

#145 [Misc] Form validation setup
  components/form/TextField.tsx
  lib/auth/validation.ts
  package.json
  pages/admin/login.tsx
  pages/api/auth/[...nextauth].ts
  yarn.lock
Labels: ready to merge ✅

#150 [Feature] Build Review Information Modal
  components/admin/requests/doctor-information/Card.tsx
  components/admin/requests/payment-information/Card.tsx
  components/admin/requests/permit-holder-information/Card.tsx
  components/admin/requests/processing/ReviewInformationModal.tsx
  components/admin/requests/processing/TasksCard.tsx
  components/admin/requests/reason-for-replacement/Card.tsx
Labels: needs dev review

#152 [Feature] Update Database schema for storing invoices
  components/admin/requests/processing/TasksCard.tsx
  lib/application-processing/resolvers.ts
  lib/application-processing/schema.ts
  lib/graphql/types.ts
  prisma/schema.prisma
  prisma/schema.sql
Labels: ready to merge ✅

#156 [Feature] Created Additional Information Card + Update Review Information Modal
  components/admin/LayoutCard.tsx
  components/admin/permit-holders/guardian-information/Card.tsx
  components/admin/requests/additional-questions/Card.tsx
  components/admin/requests/doctor-information/Card.tsx
  components/admin/requests/guardian-information/Card.tsx
  components/admin/requests/payment-information/Card.tsx
  components/admin/requests/permit-holder-information/Card.tsx
  components/admin/requests/processing/ReviewInformationModal.tsx
  components/admin/requests/processing/TasksCard.tsx
  components/admin/requests/reason-for-replacement/Card.tsx
  lib/applications/schema.ts
  lib/graphql/types.ts
  tools/admin/requests/guardian-information.ts
  tools/admin/requests/review-information.ts
Labels: don't merge, needs design review

#157 [Fix] Added Address Title to Doctor's Information Card
  components/admin/requests/doctor-information/Card.tsx
Labels: ready to merge ✅

#153 [Feature] Update Processing Tasks task approval logic/order
  components/admin/requests/processing/ReviewInformationStep.tsx
  components/admin/requests/processing/TasksCard.tsx
  lib/application-processing/resolvers.ts
  lib/application-processing/schema.ts
  lib/graphql/resolvers.ts
  lib/graphql/schema.ts
  lib/graphql/types.ts
  pages/admin/request/[id].tsx
  prisma/schema.prisma
  prisma/schema.sql
  tools/admin/requests/processing-tasks-card.ts
  tools/admin/requests/view-request.ts
Labels: ready to merge ✅

#154 [Feature] Update invoice generation API
  .gitignore
  components/admin/requests/processing/ReviewInformationStep.tsx
  components/admin/requests/processing/TasksCard.tsx
  lib/application-processing/resolvers.ts
  lib/application-processing/schema.ts
  lib/applications/field-resolvers.ts
  lib/graphql/resolvers.ts
  lib/graphql/schema.ts
  lib/graphql/type-defs.ts
  lib/graphql/types.ts
  lib/invoices/field-resolvers.ts
  lib/invoices/schema.ts
  lib/invoices/utils.ts
  package.json
  prisma/schema.prisma
  prisma/schema.sql
  temp/invoice.pdf
  tools/admin/requests/processing-tasks-card.ts
  yarn.lock
Labels: ready to merge ✅

#160 [Feature] Build Undo Confirmation Modal For Processing Tasks
  components/admin/requests/processing/ReviewInformationStep.tsx
  components/admin/requests/processing/UndoReviewRequestModal.tsx
Labels: ready to merge ✅

#161 [Feature] Server side invoice upload to S3
  .env.sample
  components/admin/requests/processing/TasksCard.tsx
  lib/application-processing/field-resolvers.ts
  lib/application-processing/resolvers.ts
  lib/application-processing/schema.ts
  lib/applications/field-resolvers.ts
  lib/graphql/resolvers.ts
  lib/graphql/types.ts
  lib/invoices/schema.ts
  lib/invoices/utils.ts
  lib/utils/format.ts
  lib/utils/s3-utils.ts
  lib/utils/upload-to-s3.ts
  package.json
  pages/admin/request/[id].tsx
  pages/admin/request/create-new.tsx
  pages/api/s3-upload.ts
  prisma/schema.prisma
  prisma/schema.sql
  tools/admin/requests/processing-tasks-card.ts
  tools/admin/requests/view-request.ts
  tools/types.ts
  yarn.lock
Labels: ready to merge ✅
